*------------------------------------------------------------*
* LOOKUP A RELATED FIELD (E.G., NAME) BASED ON INPUT FIELD
*------------------------------------------------------------*
PARAMETERS: P_KEY TYPE YOUR_TABLE-KEY_FIELD.        " INPUT FIELD (E.G., EMPLOYEE ID)
DATA:       LV_NAME TYPE YOUR_TABLE-NAME_FIELD.     " FIELD TO FETCH (E.G., EMPLOYEE NAME)

AT SELECTION-SCREEN ON P_KEY.

  CLEAR LV_NAME.  " CLEAR PREVIOUS VALUE

  SELECT SINGLE NAME_FIELD INTO LV_NAME
    FROM YOUR_TABLE
    WHERE KEY_FIELD = P_KEY.

  IF SY-SUBRC <> 0.
    MESSAGE 'NO MATCHING ENTRY FOUND.' TYPE 'I'.
    CLEAR LV_NAME.
  ELSE.
    WRITE: / 'MATCHED NAME:', LV_NAME.
  ENDIF.
